openapi: 3.0.0
info:
  title: Search Service
  version: 1.0.0
paths:
  /api/report/autocomplete:
    get:
      tags:
        - report
      operationId: reportAutocomplete
      summary: Get list of report id and report title by keywords
      parameters:
        - in: query
          name: keywords
          required: true
          schema:
            type: string
            maxLength: 20
            minLength: 1
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReportIdAndTitle'
        400:
          description: User input error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Server Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/report/{id}:
    get:
      tags:
        - report
      operationId: findById
      summary: Get report by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        400:
          description: User input error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Server Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/report/search:
    get:
      tags:
        - report
      operationId: findReports
      summary: Get reports by keywords
      parameters:
        - in: query
          name: keywords
          required: true
          schema:
            type: string
            maxLength: 20
            minLength: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
        400:
          description: User input error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Server Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Report:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        authors:
          type: array
          items:
            type: string
        target:
          type: string
        content:
          type: string
        created:
          type: string
          format: instant
    ReportIdAndTitle:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
